version: '2'

services:
    crossdock:
        image: yarpc/crossdock
        links:
            - go
            - node
            - java
            - python
        environment:
            - CROSSDOCK_CLIENTS=go,node,java,python
            - CROSSDOCK_AXIS_SERVER=go,node,java,python
            - CROSSDOCK_AXIS_BEHAVIOR=echo

    go:
        build: .
        ports:
            - 8080
            - 8081

    node:
        image: yarpc/yarpc-node
        ports:
            - 8080
            - 8081

    java:
        image: yarpc/yarpc-java
        ports:
            - 8080
            - 8081

    python:
        image: yarpc/yarpc-python
        ports:
            - 8080
            - 8081
