version: '2'

services:
    crossdock:
        image: yarpc/crossdock
        links:
            - yarpc-go
            - yarpc-node
        environment:
            - CROSSDOCK_CLIENTS=yarpc-go,yarpc-node
            - CROSSDOCK_AXIS_SERVER=yarpc-go,yarpc-node
            - CROSSDOCK_AXIS_BEHAVIOR=echo

    yarpc-go:
        build: .
        ports:
            - 8080
            - 8081

    yarpc-node:
        image: yarpc/yarpc-node
        ports:
            - 8080
            - 8081
