version: '2'

services:
    crossdock:
        image: yarpc/crossdock:v2
        links:
            - yarpc-go
            - yarpc-python
            - yarpc-node
        environment:
            - CROSSDOCK_CLIENTS=yarpc-go,yarpc-python,yarpc-node
            - CROSSDOCK_AXIS_SERVER=yarpc-go,yarpc-python,yarpc-node
            - CROSSDOCK_AXIS_BEHAVIOR=echo

    yarpc-go:
        build: .
        ports:
            - 8080
            - 8081

    yarpc-node:
        image: yarpc/yarpc-node
        ports:
            - 8080
            - 8081

    yarpc-java:
        image: yarpc/yarpc-java
        ports:
            - 8080
            - 8081

    yarpc-python:
        image: yarpc/yarpc-python:crossdock-v2
        ports:
            - 8080
            - 8081
